export interface Element {
  atomicNumber: number;
  element: string;
  symbol: string;
  atomicMass: number;
  numberOfNeutrons: number;
  numberOfProtons: number;
  numberOfElectrons: number;
  period: number;
  group?: number;
  phase: string;
  radioactive: boolean;
  natural: boolean;
  metal: boolean;
  nonmetal: boolean;
  metalloid: boolean;
  type?: string;
  atomicRadius?: number;
  electroNegativity?: number;
  firstIonization?: number;
  density?: number;
  meltingPoint?: number;
  boilingPoint?: number;
  numberOfIsotopes?: number;
  discoverer?: string;
}

// https://gist.github.com/GoodmanSciences/c2dd862cd38f21b0ad36b8f96b4bf1ee
const ELEMENTS: Element[] = [
  {
    atomicNumber: 1,
    element: "Hydrogen",
    symbol: "H",
    atomicMass: 1.007,
    numberOfNeutrons: 0,
    numberOfProtons: 1,
    numberOfElectrons: 1,
    period: 1,
    group: 1,
    phase: "gas",
    radioactive: false,
    natural: true,
    metal: false,
    nonmetal: true,
    metalloid: false,
    type: "Nonmetal",
    atomicRadius: 0.79,
    electroNegativity: 2.2,
    firstIonization: 13.5984,
    density: 0.0000899,
    meltingPoint: 14.175,
    boilingPoint: 20.28,
    numberOfIsotopes: 3,
    discoverer: "Cavendish",
  },
  {
    atomicNumber: 2,
    element: "Helium",
    symbol: "He",
    atomicMass: 4.002,
    numberOfNeutrons: 2,
    numberOfProtons: 2,
    numberOfElectrons: 2,
    period: 1,
    group: 18,
    phase: "gas",
    radioactive: false,
    natural: true,
    metal: false,
    nonmetal: true,
    metalloid: false,
    type: "Noble Gas",
    atomicRadius: 0.49,
    firstIonization: 24.5874,
    density: 0.000179,
    boilingPoint: 4.22,
    numberOfIsotopes: 5,
    discoverer: "Janssen",
  },
  {
    atomicNumber: 3,
    element: "Lithium",
    symbol: "Li",
    atomicMass: 6.941,
    numberOfNeutrons: 4,
    numberOfProtons: 3,
    numberOfElectrons: 3,
    period: 2,
    group: 1,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Alkali Metal",
    atomicRadius: 2.1,
    electroNegativity: 0.98,
    firstIonization: 5.3917,
    density: 0.534,
    meltingPoint: 453.85,
    boilingPoint: 1615,
    numberOfIsotopes: 5,
    discoverer: "Arfvedson",
  },
  {
    atomicNumber: 4,
    element: "Beryllium",
    symbol: "Be",
    atomicMass: 9.012,
    numberOfNeutrons: 5,
    numberOfProtons: 4,
    numberOfElectrons: 4,
    period: 2,
    group: 2,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Alkaline Earth Metal",
    atomicRadius: 1.4,
    electroNegativity: 1.57,
    firstIonization: 9.3227,
    density: 1.85,
    meltingPoint: 1560.15,
    boilingPoint: 2742,
    numberOfIsotopes: 6,
    discoverer: "Vaulquelin",
  },
  {
    atomicNumber: 5,
    element: "Boron",
    symbol: "B",
    atomicMass: 10.811,
    numberOfNeutrons: 6,
    numberOfProtons: 5,
    numberOfElectrons: 5,
    period: 2,
    group: 13,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: false,
    nonmetal: false,
    metalloid: true,
    type: "Metalloid",
    atomicRadius: 1.2,
    electroNegativity: 2.04,
    firstIonization: 8.298,
    density: 2.34,
    meltingPoint: 2573.15,
    boilingPoint: 4200,
    numberOfIsotopes: 6,
    discoverer: "Gay-Lussac",
  },
  {
    atomicNumber: 6,
    element: "Carbon",
    symbol: "C",
    atomicMass: 12.011,
    numberOfNeutrons: 6,
    numberOfProtons: 6,
    numberOfElectrons: 6,
    period: 2,
    group: 14,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: false,
    nonmetal: true,
    metalloid: false,
    type: "Nonmetal",
    atomicRadius: 0.91,
    electroNegativity: 2.55,
    firstIonization: 11.2603,
    density: 2.27,
    meltingPoint: 3948.15,
    boilingPoint: 4300,
    numberOfIsotopes: 7,
    discoverer: "Prehistoric",
  },
  {
    atomicNumber: 7,
    element: "Nitrogen",
    symbol: "N",
    atomicMass: 14.007,
    numberOfNeutrons: 7,
    numberOfProtons: 7,
    numberOfElectrons: 7,
    period: 2,
    group: 15,
    phase: "gas",
    radioactive: false,
    natural: true,
    metal: false,
    nonmetal: true,
    metalloid: false,
    type: "Nonmetal",
    atomicRadius: 0.75,
    electroNegativity: 3.04,
    firstIonization: 14.5341,
    density: 0.00125,
    meltingPoint: 63.29,
    boilingPoint: 77.36,
    numberOfIsotopes: 8,
    discoverer: "Rutherford",
  },
  {
    atomicNumber: 8,
    element: "Oxygen",
    symbol: "O",
    atomicMass: 15.999,
    numberOfNeutrons: 8,
    numberOfProtons: 8,
    numberOfElectrons: 8,
    period: 2,
    group: 16,
    phase: "gas",
    radioactive: false,
    natural: true,
    metal: false,
    nonmetal: true,
    metalloid: false,
    type: "Nonmetal",
    atomicRadius: 0.65,
    electroNegativity: 3.44,
    firstIonization: 13.6181,
    density: 0.00143,
    meltingPoint: 50.5,
    boilingPoint: 90.2,
    numberOfIsotopes: 8,
    discoverer: "Priestley/Scheele",
  },
  {
    atomicNumber: 9,
    element: "Fluorine",
    symbol: "F",
    atomicMass: 18.998,
    numberOfNeutrons: 10,
    numberOfProtons: 9,
    numberOfElectrons: 9,
    period: 2,
    group: 17,
    phase: "gas",
    radioactive: false,
    natural: true,
    metal: false,
    nonmetal: true,
    metalloid: false,
    type: "Halogen",
    atomicRadius: 0.57,
    electroNegativity: 3.98,
    firstIonization: 17.4228,
    density: 0.0017,
    meltingPoint: 53.63,
    boilingPoint: 85.03,
    numberOfIsotopes: 6,
    discoverer: "Moissan",
  },
  {
    atomicNumber: 10,
    element: "Neon",
    symbol: "Ne",
    atomicMass: 20.18,
    numberOfNeutrons: 10,
    numberOfProtons: 10,
    numberOfElectrons: 10,
    period: 2,
    group: 18,
    phase: "gas",
    radioactive: false,
    natural: true,
    metal: false,
    nonmetal: true,
    metalloid: false,
    type: "Noble Gas",
    atomicRadius: 0.51,
    firstIonization: 21.5645,
    density: 0.0009,
    meltingPoint: 24.703,
    boilingPoint: 27.07,
    numberOfIsotopes: 8,
    discoverer: "Ramsay and Travers",
  },
  {
    atomicNumber: 11,
    element: "Sodium",
    symbol: "Na",
    atomicMass: 22.99,
    numberOfNeutrons: 12,
    numberOfProtons: 11,
    numberOfElectrons: 11,
    period: 3,
    group: 1,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Alkali Metal",
    atomicRadius: 2.2,
    electroNegativity: 0.93,
    firstIonization: 5.1391,
    density: 0.971,
    meltingPoint: 371.15,
    boilingPoint: 1156,
    numberOfIsotopes: 7,
    discoverer: "Davy",
  },
  {
    atomicNumber: 12,
    element: "Magnesium",
    symbol: "Mg",
    atomicMass: 24.305,
    numberOfNeutrons: 12,
    numberOfProtons: 12,
    numberOfElectrons: 12,
    period: 3,
    group: 2,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Alkaline Earth Metal",
    atomicRadius: 1.7,
    electroNegativity: 1.31,
    firstIonization: 7.6462,
    density: 1.74,
    meltingPoint: 923.15,
    boilingPoint: 1363,
    numberOfIsotopes: 8,
    discoverer: "Black",
  },
  {
    atomicNumber: 13,
    element: "Aluminum",
    symbol: "Al",
    atomicMass: 26.982,
    numberOfNeutrons: 14,
    numberOfProtons: 13,
    numberOfElectrons: 13,
    period: 3,
    group: 13,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Metal",
    atomicRadius: 1.8,
    electroNegativity: 1.61,
    firstIonization: 5.9858,
    density: 2.7,
    meltingPoint: 933.4,
    boilingPoint: 2792,
    numberOfIsotopes: 8,
    discoverer: "Wshler",
  },
  {
    atomicNumber: 14,
    element: "Silicon",
    symbol: "Si",
    atomicMass: 28.086,
    numberOfNeutrons: 14,
    numberOfProtons: 14,
    numberOfElectrons: 14,
    period: 3,
    group: 14,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: false,
    nonmetal: false,
    metalloid: true,
    type: "Metalloid",
    atomicRadius: 1.5,
    electroNegativity: 1.9,
    firstIonization: 8.1517,
    density: 2.33,
    meltingPoint: 1683.15,
    boilingPoint: 3538,
    numberOfIsotopes: 8,
    discoverer: "Berzelius",
  },
  {
    atomicNumber: 15,
    element: "Phosphorus",
    symbol: "P",
    atomicMass: 30.974,
    numberOfNeutrons: 16,
    numberOfProtons: 15,
    numberOfElectrons: 15,
    period: 3,
    group: 15,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: false,
    nonmetal: true,
    metalloid: false,
    type: "Nonmetal",
    atomicRadius: 1.2,
    electroNegativity: 2.19,
    firstIonization: 10.4867,
    density: 1.82,
    meltingPoint: 317.25,
    boilingPoint: 553,
    numberOfIsotopes: 7,
    discoverer: "BranBrand",
  },
  {
    atomicNumber: 16,
    element: "Sulfur",
    symbol: "S",
    atomicMass: 32.065,
    numberOfNeutrons: 16,
    numberOfProtons: 16,
    numberOfElectrons: 16,
    period: 3,
    group: 16,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: false,
    nonmetal: true,
    metalloid: false,
    type: "Nonmetal",
    atomicRadius: 1.1,
    electroNegativity: 2.58,
    firstIonization: 10.36,
    density: 2.07,
    meltingPoint: 388.51,
    boilingPoint: 717.8,
    numberOfIsotopes: 10,
    discoverer: "Prehistoric",
  },
  {
    atomicNumber: 17,
    element: "Chlorine",
    symbol: "Cl",
    atomicMass: 35.453,
    numberOfNeutrons: 18,
    numberOfProtons: 17,
    numberOfElectrons: 17,
    period: 3,
    group: 17,
    phase: "gas",
    radioactive: false,
    natural: true,
    metal: false,
    nonmetal: true,
    metalloid: false,
    type: "Halogen",
    atomicRadius: 0.97,
    electroNegativity: 3.16,
    firstIonization: 12.9676,
    density: 0.00321,
    meltingPoint: 172.31,
    boilingPoint: 239.11,
    numberOfIsotopes: 11,
    discoverer: "Scheele",
  },
  {
    atomicNumber: 18,
    element: "Argon",
    symbol: "Ar",
    atomicMass: 39.948,
    numberOfNeutrons: 22,
    numberOfProtons: 18,
    numberOfElectrons: 18,
    period: 3,
    group: 18,
    phase: "gas",
    radioactive: false,
    natural: true,
    metal: false,
    nonmetal: true,
    metalloid: false,
    type: "Noble Gas",
    atomicRadius: 0.88,
    firstIonization: 15.7596,
    density: 0.00178,
    meltingPoint: 83.96,
    boilingPoint: 87.3,
    numberOfIsotopes: 8,
    discoverer: "Rayleigh and Ramsay",
  },
  {
    atomicNumber: 19,
    element: "Potassium",
    symbol: "K",
    atomicMass: 39.098,
    numberOfNeutrons: 20,
    numberOfProtons: 19,
    numberOfElectrons: 19,
    period: 4,
    group: 1,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Alkali Metal",
    atomicRadius: 2.8,
    electroNegativity: 0.82,
    firstIonization: 4.3407,
    density: 0.862,
    meltingPoint: 336.5,
    boilingPoint: 1032,
    numberOfIsotopes: 10,
    discoverer: "Davy",
  },
  {
    atomicNumber: 20,
    element: "Calcium",
    symbol: "Ca",
    atomicMass: 40.078,
    numberOfNeutrons: 20,
    numberOfProtons: 20,
    numberOfElectrons: 20,
    period: 4,
    group: 2,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Alkaline Earth Metal",
    atomicRadius: 2.2,
    electroNegativity: 1,
    firstIonization: 6.1132,
    density: 1.54,
    meltingPoint: 1112.15,
    boilingPoint: 1757,
    numberOfIsotopes: 14,
    discoverer: "Davy",
  },
  {
    atomicNumber: 21,
    element: "Scandium",
    symbol: "Sc",
    atomicMass: 44.956,
    numberOfNeutrons: 24,
    numberOfProtons: 21,
    numberOfElectrons: 21,
    period: 4,
    group: 3,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Transition Metal",
    atomicRadius: 2.1,
    electroNegativity: 1.36,
    firstIonization: 6.5615,
    density: 2.99,
    meltingPoint: 1812.15,
    boilingPoint: 3109,
    numberOfIsotopes: 15,
    discoverer: "Nilson",
  },
  {
    atomicNumber: 22,
    element: "Titanium",
    symbol: "Ti",
    atomicMass: 47.867,
    numberOfNeutrons: 26,
    numberOfProtons: 22,
    numberOfElectrons: 22,
    period: 4,
    group: 4,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Transition Metal",
    atomicRadius: 2,
    electroNegativity: 1.54,
    firstIonization: 6.8281,
    density: 4.54,
    meltingPoint: 1933.15,
    boilingPoint: 3560,
    numberOfIsotopes: 9,
    discoverer: "Gregor",
  },
  {
    atomicNumber: 23,
    element: "Vanadium",
    symbol: "V",
    atomicMass: 50.942,
    numberOfNeutrons: 28,
    numberOfProtons: 23,
    numberOfElectrons: 23,
    period: 4,
    group: 5,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Transition Metal",
    atomicRadius: 1.9,
    electroNegativity: 1.63,
    firstIonization: 6.7462,
    density: 6.11,
    meltingPoint: 2175.15,
    boilingPoint: 3680,
    numberOfIsotopes: 9,
    discoverer: "del Rio",
  },
  {
    atomicNumber: 24,
    element: "Chromium",
    symbol: "Cr",
    atomicMass: 51.996,
    numberOfNeutrons: 28,
    numberOfProtons: 24,
    numberOfElectrons: 24,
    period: 4,
    group: 6,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Transition Metal",
    atomicRadius: 1.9,
    electroNegativity: 1.66,
    firstIonization: 6.7665,
    density: 7.15,
    meltingPoint: 2130.15,
    boilingPoint: 2944,
    numberOfIsotopes: 9,
    discoverer: "Vauquelin",
  },
  {
    atomicNumber: 25,
    element: "Manganese",
    symbol: "Mn",
    atomicMass: 54.938,
    numberOfNeutrons: 30,
    numberOfProtons: 25,
    numberOfElectrons: 25,
    period: 4,
    group: 7,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Transition Metal",
    atomicRadius: 1.8,
    electroNegativity: 1.55,
    firstIonization: 7.434,
    density: 7.44,
    meltingPoint: 1519.15,
    boilingPoint: 2334,
    numberOfIsotopes: 11,
    discoverer: "Gahn, Scheele",
  },
  {
    atomicNumber: 26,
    element: "Iron",
    symbol: "Fe",
    atomicMass: 55.845,
    numberOfNeutrons: 30,
    numberOfProtons: 26,
    numberOfElectrons: 26,
    period: 4,
    group: 8,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Transition Metal",
    atomicRadius: 1.7,
    electroNegativity: 1.83,
    firstIonization: 7.9024,
    density: 7.87,
    meltingPoint: 1808.15,
    boilingPoint: 3134,
    numberOfIsotopes: 10,
    discoverer: "Prehistoric",
  },
  {
    atomicNumber: 27,
    element: "Cobalt",
    symbol: "Co",
    atomicMass: 58.933,
    numberOfNeutrons: 32,
    numberOfProtons: 27,
    numberOfElectrons: 27,
    period: 4,
    group: 9,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Transition Metal",
    atomicRadius: 1.7,
    electroNegativity: 1.88,
    firstIonization: 7.881,
    density: 8.86,
    meltingPoint: 1768.15,
    boilingPoint: 3200,
    numberOfIsotopes: 14,
    discoverer: "Brandt",
  },
  {
    atomicNumber: 28,
    element: "Nickel",
    symbol: "Ni",
    atomicMass: 58.693,
    numberOfNeutrons: 31,
    numberOfProtons: 28,
    numberOfElectrons: 28,
    period: 4,
    group: 10,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Transition Metal",
    atomicRadius: 1.6,
    electroNegativity: 1.91,
    firstIonization: 7.6398,
    density: 8.91,
    meltingPoint: 1726.15,
    boilingPoint: 3186,
    numberOfIsotopes: 11,
    discoverer: "Cronstedt",
  },
  {
    atomicNumber: 29,
    element: "Copper",
    symbol: "Cu",
    atomicMass: 63.546,
    numberOfNeutrons: 35,
    numberOfProtons: 29,
    numberOfElectrons: 29,
    period: 4,
    group: 11,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Transition Metal",
    atomicRadius: 1.6,
    electroNegativity: 1.9,
    firstIonization: 7.7264,
    density: 8.96,
    meltingPoint: 1357.75,
    boilingPoint: 2835,
    numberOfIsotopes: 11,
    discoverer: "Prehistoric",
  },
  {
    atomicNumber: 30,
    element: "Zinc",
    symbol: "Zn",
    atomicMass: 65.38,
    numberOfNeutrons: 35,
    numberOfProtons: 30,
    numberOfElectrons: 30,
    period: 4,
    group: 12,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Transition Metal",
    atomicRadius: 1.5,
    electroNegativity: 1.65,
    firstIonization: 9.3942,
    density: 7.13,
    meltingPoint: 692.88,
    boilingPoint: 1180,
    numberOfIsotopes: 15,
    discoverer: "Prehistoric",
  },
  {
    atomicNumber: 31,
    element: "Gallium",
    symbol: "Ga",
    atomicMass: 69.723,
    numberOfNeutrons: 39,
    numberOfProtons: 31,
    numberOfElectrons: 31,
    period: 4,
    group: 13,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Metal",
    atomicRadius: 1.8,
    electroNegativity: 1.81,
    firstIonization: 5.9993,
    density: 5.91,
    meltingPoint: 302.91,
    boilingPoint: 2477,
    numberOfIsotopes: 14,
    discoverer: "de Boisbaudran",
  },
  {
    atomicNumber: 32,
    element: "Germanium",
    symbol: "Ge",
    atomicMass: 72.64,
    numberOfNeutrons: 41,
    numberOfProtons: 32,
    numberOfElectrons: 32,
    period: 4,
    group: 14,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: false,
    nonmetal: false,
    metalloid: true,
    type: "Metalloid",
    atomicRadius: 1.5,
    electroNegativity: 2.01,
    firstIonization: 7.8994,
    density: 5.32,
    meltingPoint: 1211.45,
    boilingPoint: 3106,
    numberOfIsotopes: 17,
    discoverer: "Winkler",
  },
  {
    atomicNumber: 33,
    element: "Arsenic",
    symbol: "As",
    atomicMass: 74.922,
    numberOfNeutrons: 42,
    numberOfProtons: 33,
    numberOfElectrons: 33,
    period: 4,
    group: 15,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: false,
    nonmetal: false,
    metalloid: true,
    type: "Metalloid",
    atomicRadius: 1.3,
    electroNegativity: 2.18,
    firstIonization: 9.7886,
    density: 5.78,
    meltingPoint: 1090.15,
    boilingPoint: 887,
    numberOfIsotopes: 14,
    discoverer: "Albertus Magnus",
  },
  {
    atomicNumber: 34,
    element: "Selenium",
    symbol: "Se",
    atomicMass: 78.96,
    numberOfNeutrons: 45,
    numberOfProtons: 34,
    numberOfElectrons: 34,
    period: 4,
    group: 16,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: false,
    nonmetal: true,
    metalloid: false,
    type: "Nonmetal",
    atomicRadius: 1.2,
    electroNegativity: 2.55,
    firstIonization: 9.7524,
    density: 4.81,
    meltingPoint: 494.15,
    boilingPoint: 958,
    numberOfIsotopes: 20,
    discoverer: "Berzelius",
  },
  {
    atomicNumber: 35,
    element: "Bromine",
    symbol: "Br",
    atomicMass: 79.904,
    numberOfNeutrons: 45,
    numberOfProtons: 35,
    numberOfElectrons: 35,
    period: 4,
    group: 17,
    phase: "liq",
    radioactive: false,
    natural: true,
    metal: false,
    nonmetal: true,
    metalloid: false,
    type: "Halogen",
    atomicRadius: 1.1,
    electroNegativity: 2.96,
    firstIonization: 11.8138,
    density: 3.12,
    meltingPoint: 266.05,
    boilingPoint: 332,
    numberOfIsotopes: 19,
    discoverer: "Balard",
  },
  {
    atomicNumber: 36,
    element: "Krypton",
    symbol: "Kr",
    atomicMass: 83.798,
    numberOfNeutrons: 48,
    numberOfProtons: 36,
    numberOfElectrons: 36,
    period: 4,
    group: 18,
    phase: "gas",
    radioactive: false,
    natural: true,
    metal: false,
    nonmetal: true,
    metalloid: false,
    type: "Noble Gas",
    atomicRadius: 1,
    firstIonization: 13.9996,
    density: 0.00373,
    meltingPoint: 115.93,
    boilingPoint: 119.93,
    numberOfIsotopes: 23,
    discoverer: "Ramsay and Travers",
  },
  {
    atomicNumber: 37,
    element: "Rubidium",
    symbol: "Rb",
    atomicMass: 85.468,
    numberOfNeutrons: 48,
    numberOfProtons: 37,
    numberOfElectrons: 37,
    period: 5,
    group: 1,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Alkali Metal",
    atomicRadius: 3,
    electroNegativity: 0.82,
    firstIonization: 4.1771,
    density: 1.53,
    meltingPoint: 312.79,
    boilingPoint: 961,
    numberOfIsotopes: 20,
    discoverer: "Bunsen and Kirchoff",
  },
  {
    atomicNumber: 38,
    element: "Strontium",
    symbol: "Sr",
    atomicMass: 87.62,
    numberOfNeutrons: 50,
    numberOfProtons: 38,
    numberOfElectrons: 38,
    period: 5,
    group: 2,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Alkaline Earth Metal",
    atomicRadius: 2.5,
    electroNegativity: 0.95,
    firstIonization: 5.6949,
    density: 2.64,
    meltingPoint: 1042.15,
    boilingPoint: 1655,
    numberOfIsotopes: 18,
    discoverer: "Davy",
  },
  {
    atomicNumber: 39,
    element: "Yttrium",
    symbol: "Y",
    atomicMass: 88.906,
    numberOfNeutrons: 50,
    numberOfProtons: 39,
    numberOfElectrons: 39,
    period: 5,
    group: 3,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Transition Metal",
    atomicRadius: 2.3,
    electroNegativity: 1.22,
    firstIonization: 6.2173,
    density: 4.47,
    meltingPoint: 1799.15,
    boilingPoint: 3609,
    numberOfIsotopes: 21,
    discoverer: "Gadolin",
  },
  {
    atomicNumber: 40,
    element: "Zirconium",
    symbol: "Zr",
    atomicMass: 91.224,
    numberOfNeutrons: 51,
    numberOfProtons: 40,
    numberOfElectrons: 40,
    period: 5,
    group: 4,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Transition Metal",
    atomicRadius: 2.2,
    electroNegativity: 1.33,
    firstIonization: 6.6339,
    density: 6.51,
    meltingPoint: 2125.15,
    boilingPoint: 4682,
    numberOfIsotopes: 20,
    discoverer: "Klaproth",
  },
  {
    atomicNumber: 41,
    element: "Niobium",
    symbol: "Nb",
    atomicMass: 92.906,
    numberOfNeutrons: 52,
    numberOfProtons: 41,
    numberOfElectrons: 41,
    period: 5,
    group: 5,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Transition Metal",
    atomicRadius: 2.1,
    electroNegativity: 1.6,
    firstIonization: 6.7589,
    density: 8.57,
    meltingPoint: 2741.15,
    boilingPoint: 5017,
    numberOfIsotopes: 24,
    discoverer: "Hatchett",
  },
  {
    atomicNumber: 42,
    element: "Molybdenum",
    symbol: "Mo",
    atomicMass: 95.96,
    numberOfNeutrons: 54,
    numberOfProtons: 42,
    numberOfElectrons: 42,
    period: 5,
    group: 6,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Transition Metal",
    atomicRadius: 2,
    electroNegativity: 2.16,
    firstIonization: 7.0924,
    density: 10.2,
    meltingPoint: 2890.15,
    boilingPoint: 4912,
    numberOfIsotopes: 20,
    discoverer: "Scheele",
  },
  {
    atomicNumber: 43,
    element: "Technetium",
    symbol: "Tc",
    atomicMass: 98,
    numberOfNeutrons: 55,
    numberOfProtons: 43,
    numberOfElectrons: 43,
    period: 5,
    group: 7,
    phase: "artificial",
    radioactive: true,
    natural: false,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Transition Metal",
    atomicRadius: 2,
    electroNegativity: 1.9,
    firstIonization: 7.28,
    density: 11.5,
    meltingPoint: 2473.15,
    boilingPoint: 5150,
    numberOfIsotopes: 23,
    discoverer: "Perrier and Segr�",
  },
  {
    atomicNumber: 44,
    element: "Ruthenium",
    symbol: "Ru",
    atomicMass: 101.07,
    numberOfNeutrons: 57,
    numberOfProtons: 44,
    numberOfElectrons: 44,
    period: 5,
    group: 8,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Transition Metal",
    atomicRadius: 1.9,
    electroNegativity: 2.2,
    firstIonization: 7.3605,
    density: 12.4,
    meltingPoint: 2523.15,
    boilingPoint: 4423,
    numberOfIsotopes: 16,
    discoverer: "Klaus",
  },
  {
    atomicNumber: 45,
    element: "Rhodium",
    symbol: "Rh",
    atomicMass: 102.906,
    numberOfNeutrons: 58,
    numberOfProtons: 45,
    numberOfElectrons: 45,
    period: 5,
    group: 9,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Transition Metal",
    atomicRadius: 1.8,
    electroNegativity: 2.28,
    firstIonization: 7.4589,
    density: 12.4,
    meltingPoint: 2239.15,
    boilingPoint: 3968,
    numberOfIsotopes: 20,
    discoverer: "Wollaston",
  },
  {
    atomicNumber: 46,
    element: "Palladium",
    symbol: "Pd",
    atomicMass: 106.42,
    numberOfNeutrons: 60,
    numberOfProtons: 46,
    numberOfElectrons: 46,
    period: 5,
    group: 10,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Transition Metal",
    atomicRadius: 1.8,
    electroNegativity: 2.2,
    firstIonization: 8.3369,
    density: 12,
    meltingPoint: 1825.15,
    boilingPoint: 3236,
    numberOfIsotopes: 21,
    discoverer: "Wollaston",
  },
  {
    atomicNumber: 47,
    element: "Silver",
    symbol: "Ag",
    atomicMass: 107.868,
    numberOfNeutrons: 61,
    numberOfProtons: 47,
    numberOfElectrons: 47,
    period: 5,
    group: 11,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Transition Metal",
    atomicRadius: 1.8,
    electroNegativity: 1.93,
    firstIonization: 7.5762,
    density: 10.5,
    meltingPoint: 1234.15,
    boilingPoint: 2435,
    numberOfIsotopes: 27,
    discoverer: "Prehistoric",
  },
  {
    atomicNumber: 48,
    element: "Cadmium",
    symbol: "Cd",
    atomicMass: 112.411,
    numberOfNeutrons: 64,
    numberOfProtons: 48,
    numberOfElectrons: 48,
    period: 5,
    group: 12,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Transition Metal",
    atomicRadius: 1.7,
    electroNegativity: 1.69,
    firstIonization: 8.9938,
    density: 8.69,
    meltingPoint: 594.33,
    boilingPoint: 1040,
    numberOfIsotopes: 22,
    discoverer: "Stromeyer",
  },
  {
    atomicNumber: 49,
    element: "Indium",
    symbol: "In",
    atomicMass: 114.818,
    numberOfNeutrons: 66,
    numberOfProtons: 49,
    numberOfElectrons: 49,
    period: 5,
    group: 13,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Metal",
    atomicRadius: 2,
    electroNegativity: 1.78,
    firstIonization: 5.7864,
    density: 7.31,
    meltingPoint: 429.91,
    boilingPoint: 2345,
    numberOfIsotopes: 34,
    discoverer: "Reich and Richter",
  },
  {
    atomicNumber: 50,
    element: "Tin",
    symbol: "Sn",
    atomicMass: 118.71,
    numberOfNeutrons: 69,
    numberOfProtons: 50,
    numberOfElectrons: 50,
    period: 5,
    group: 14,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Metal",
    atomicRadius: 1.7,
    electroNegativity: 1.96,
    firstIonization: 7.3439,
    density: 7.29,
    meltingPoint: 505.21,
    boilingPoint: 2875,
    numberOfIsotopes: 28,
    discoverer: "Prehistoric",
  },
  {
    atomicNumber: 51,
    element: "Antimony",
    symbol: "Sb",
    atomicMass: 121.76,
    numberOfNeutrons: 71,
    numberOfProtons: 51,
    numberOfElectrons: 51,
    period: 5,
    group: 15,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: false,
    nonmetal: false,
    metalloid: true,
    type: "Metalloid",
    atomicRadius: 1.5,
    electroNegativity: 2.05,
    firstIonization: 8.6084,
    density: 6.69,
    meltingPoint: 904.05,
    boilingPoint: 1860,
    numberOfIsotopes: 29,
    discoverer: "Early historic times",
  },
  {
    atomicNumber: 52,
    element: "Tellurium",
    symbol: "Te",
    atomicMass: 127.6,
    numberOfNeutrons: 76,
    numberOfProtons: 52,
    numberOfElectrons: 52,
    period: 5,
    group: 16,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: false,
    nonmetal: false,
    metalloid: true,
    type: "Metalloid",
    atomicRadius: 1.4,
    electroNegativity: 2.1,
    firstIonization: 9.0096,
    density: 6.23,
    meltingPoint: 722.8,
    boilingPoint: 1261,
    numberOfIsotopes: 29,
    discoverer: "von Reichenstein",
  },
  {
    atomicNumber: 53,
    element: "Iodine",
    symbol: "I",
    atomicMass: 126.904,
    numberOfNeutrons: 74,
    numberOfProtons: 53,
    numberOfElectrons: 53,
    period: 5,
    group: 17,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: false,
    nonmetal: true,
    metalloid: false,
    type: "Halogen",
    atomicRadius: 1.3,
    electroNegativity: 2.66,
    firstIonization: 10.4513,
    density: 4.93,
    meltingPoint: 386.65,
    boilingPoint: 457.4,
    numberOfIsotopes: 24,
    discoverer: "Courtois",
  },
  {
    atomicNumber: 54,
    element: "Xenon",
    symbol: "Xe",
    atomicMass: 131.293,
    numberOfNeutrons: 77,
    numberOfProtons: 54,
    numberOfElectrons: 54,
    period: 5,
    group: 18,
    phase: "gas",
    radioactive: false,
    natural: true,
    metal: false,
    nonmetal: true,
    metalloid: false,
    type: "Noble Gas",
    atomicRadius: 1.2,
    firstIonization: 12.1298,
    density: 0.00589,
    meltingPoint: 161.45,
    boilingPoint: 165.03,
    numberOfIsotopes: 31,
    discoverer: "Ramsay and Travers",
  },
  {
    atomicNumber: 55,
    element: "Cesium",
    symbol: "Cs",
    atomicMass: 132.905,
    numberOfNeutrons: 78,
    numberOfProtons: 55,
    numberOfElectrons: 55,
    period: 6,
    group: 1,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Alkali Metal",
    atomicRadius: 3.3,
    electroNegativity: 0.79,
    firstIonization: 3.8939,
    density: 1.87,
    meltingPoint: 301.7,
    boilingPoint: 944,
    numberOfIsotopes: 22,
    discoverer: "Bunsen and Kirchoff",
  },
  {
    atomicNumber: 56,
    element: "Barium",
    symbol: "Ba",
    atomicMass: 137.327,
    numberOfNeutrons: 81,
    numberOfProtons: 56,
    numberOfElectrons: 56,
    period: 6,
    group: 2,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Alkaline Earth Metal",
    atomicRadius: 2.8,
    electroNegativity: 0.89,
    firstIonization: 5.2117,
    density: 3.59,
    meltingPoint: 1002.15,
    boilingPoint: 2170,
    numberOfIsotopes: 25,
    discoverer: "Davy",
  },
  {
    atomicNumber: 57,
    element: "Lanthanum",
    symbol: "La",
    atomicMass: 138.905,
    numberOfNeutrons: 82,
    numberOfProtons: 57,
    numberOfElectrons: 57,
    period: 6,
    group: 3,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Lanthanide",
    atomicRadius: 2.7,
    electroNegativity: 1.1,
    firstIonization: 5.5769,
    density: 6.15,
    meltingPoint: 1193.15,
    boilingPoint: 3737,
    numberOfIsotopes: 19,
    discoverer: "Mosander",
  },
  {
    atomicNumber: 58,
    element: "Cerium",
    symbol: "Ce",
    atomicMass: 140.116,
    numberOfNeutrons: 82,
    numberOfProtons: 58,
    numberOfElectrons: 58,
    period: 6,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Lanthanide",
    atomicRadius: 2.7,
    electroNegativity: 1.12,
    firstIonization: 5.5387,
    density: 6.77,
    meltingPoint: 1071.15,
    boilingPoint: 3716,
    numberOfIsotopes: 19,
    discoverer: "Berzelius",
  },
  {
    atomicNumber: 59,
    element: "Praseodymium",
    symbol: "Pr",
    atomicMass: 140.908,
    numberOfNeutrons: 82,
    numberOfProtons: 59,
    numberOfElectrons: 59,
    period: 6,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Lanthanide",
    atomicRadius: 2.7,
    electroNegativity: 1.13,
    firstIonization: 5.473,
    density: 6.77,
    meltingPoint: 1204.15,
    boilingPoint: 3793,
    numberOfIsotopes: 15,
    discoverer: "von Welsbach",
  },
  {
    atomicNumber: 60,
    element: "Neodymium",
    symbol: "Nd",
    atomicMass: 144.242,
    numberOfNeutrons: 84,
    numberOfProtons: 60,
    numberOfElectrons: 60,
    period: 6,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Lanthanide",
    atomicRadius: 2.6,
    electroNegativity: 1.14,
    firstIonization: 5.525,
    density: 7.01,
    meltingPoint: 1289.15,
    boilingPoint: 3347,
    numberOfIsotopes: 16,
    discoverer: "von Welsbach",
  },
  {
    atomicNumber: 61,
    element: "Promethium",
    symbol: "Pm",
    atomicMass: 145,
    numberOfNeutrons: 84,
    numberOfProtons: 61,
    numberOfElectrons: 61,
    period: 6,
    phase: "artificial",
    radioactive: true,
    natural: false,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Lanthanide",
    atomicRadius: 2.6,
    electroNegativity: 1.13,
    firstIonization: 5.582,
    density: 7.26,
    meltingPoint: 1204.15,
    boilingPoint: 3273,
    numberOfIsotopes: 14,
    discoverer: "Marinsky et al.",
  },
  {
    atomicNumber: 62,
    element: "Samarium",
    symbol: "Sm",
    atomicMass: 150.36,
    numberOfNeutrons: 88,
    numberOfProtons: 62,
    numberOfElectrons: 62,
    period: 6,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Lanthanide",
    atomicRadius: 2.6,
    electroNegativity: 1.17,
    firstIonization: 5.6437,
    density: 7.52,
    meltingPoint: 1345.15,
    boilingPoint: 2067,
    numberOfIsotopes: 17,
    discoverer: "Boisbaudran",
  },
  {
    atomicNumber: 63,
    element: "Europium",
    symbol: "Eu",
    atomicMass: 151.964,
    numberOfNeutrons: 89,
    numberOfProtons: 63,
    numberOfElectrons: 63,
    period: 6,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Lanthanide",
    atomicRadius: 2.6,
    electroNegativity: 1.2,
    firstIonization: 5.6704,
    density: 5.24,
    meltingPoint: 1095.15,
    boilingPoint: 1802,
    numberOfIsotopes: 21,
    discoverer: "Demarcay",
  },
  {
    atomicNumber: 64,
    element: "Gadolinium",
    symbol: "Gd",
    atomicMass: 157.25,
    numberOfNeutrons: 93,
    numberOfProtons: 64,
    numberOfElectrons: 64,
    period: 6,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Lanthanide",
    atomicRadius: 2.5,
    electroNegativity: 1.2,
    firstIonization: 6.1501,
    density: 7.9,
    meltingPoint: 1585.15,
    boilingPoint: 3546,
    numberOfIsotopes: 17,
    discoverer: "de Marignac",
  },
  {
    atomicNumber: 65,
    element: "Terbium",
    symbol: "Tb",
    atomicMass: 158.925,
    numberOfNeutrons: 94,
    numberOfProtons: 65,
    numberOfElectrons: 65,
    period: 6,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Lanthanide",
    atomicRadius: 2.5,
    electroNegativity: 1.2,
    firstIonization: 5.8638,
    density: 8.23,
    meltingPoint: 1630.15,
    boilingPoint: 3503,
    numberOfIsotopes: 24,
    discoverer: "Mosander",
  },
  {
    atomicNumber: 66,
    element: "Dysprosium",
    symbol: "Dy",
    atomicMass: 162.5,
    numberOfNeutrons: 97,
    numberOfProtons: 66,
    numberOfElectrons: 66,
    period: 6,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Lanthanide",
    atomicRadius: 2.5,
    electroNegativity: 1.22,
    firstIonization: 5.9389,
    density: 8.55,
    meltingPoint: 1680.15,
    boilingPoint: 2840,
    numberOfIsotopes: 21,
    discoverer: "de Boisbaudran",
  },
  {
    atomicNumber: 67,
    element: "Holmium",
    symbol: "Ho",
    atomicMass: 164.93,
    numberOfNeutrons: 98,
    numberOfProtons: 67,
    numberOfElectrons: 67,
    period: 6,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Lanthanide",
    atomicRadius: 2.5,
    electroNegativity: 1.23,
    firstIonization: 6.0215,
    density: 8.8,
    meltingPoint: 1743.15,
    boilingPoint: 2993,
    numberOfIsotopes: 29,
    discoverer: "Delafontaine and Soret",
  },
  {
    atomicNumber: 68,
    element: "Erbium",
    symbol: "Er",
    atomicMass: 167.259,
    numberOfNeutrons: 99,
    numberOfProtons: 68,
    numberOfElectrons: 68,
    period: 6,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Lanthanide",
    atomicRadius: 2.5,
    electroNegativity: 1.24,
    firstIonization: 6.1077,
    density: 9.07,
    meltingPoint: 1795.15,
    boilingPoint: 3503,
    numberOfIsotopes: 16,
    discoverer: "Mosander",
  },
  {
    atomicNumber: 69,
    element: "Thulium",
    symbol: "Tm",
    atomicMass: 168.934,
    numberOfNeutrons: 100,
    numberOfProtons: 69,
    numberOfElectrons: 69,
    period: 6,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Lanthanide",
    atomicRadius: 2.4,
    electroNegativity: 1.25,
    firstIonization: 6.1843,
    density: 9.32,
    meltingPoint: 1818.15,
    boilingPoint: 2223,
    numberOfIsotopes: 18,
    discoverer: "Cleve",
  },
  {
    atomicNumber: 70,
    element: "Ytterbium",
    symbol: "Yb",
    atomicMass: 173.054,
    numberOfNeutrons: 103,
    numberOfProtons: 70,
    numberOfElectrons: 70,
    period: 6,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Lanthanide",
    atomicRadius: 2.4,
    electroNegativity: 1.1,
    firstIonization: 6.2542,
    density: 6.97,
    meltingPoint: 1097.15,
    boilingPoint: 1469,
    numberOfIsotopes: 16,
    discoverer: "Marignac",
  },
  {
    atomicNumber: 71,
    element: "Lutetium",
    symbol: "Lu",
    atomicMass: 174.967,
    numberOfNeutrons: 104,
    numberOfProtons: 71,
    numberOfElectrons: 71,
    period: 6,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Lanthanide",
    atomicRadius: 2.3,
    electroNegativity: 1.27,
    firstIonization: 5.4259,
    density: 9.84,
    meltingPoint: 1936.15,
    boilingPoint: 3675,
    numberOfIsotopes: 22,
    discoverer: "Urbain/ von Welsbach",
  },
  {
    atomicNumber: 72,
    element: "Hafnium",
    symbol: "Hf",
    atomicMass: 178.49,
    numberOfNeutrons: 106,
    numberOfProtons: 72,
    numberOfElectrons: 72,
    period: 6,
    group: 4,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Transition Metal",
    atomicRadius: 2.2,
    electroNegativity: 1.3,
    firstIonization: 6.8251,
    density: 13.3,
    meltingPoint: 2500.15,
    boilingPoint: 4876,
    numberOfIsotopes: 17,
    discoverer: "Coster and von Hevesy",
  },
  {
    atomicNumber: 73,
    element: "Tantalum",
    symbol: "Ta",
    atomicMass: 180.948,
    numberOfNeutrons: 108,
    numberOfProtons: 73,
    numberOfElectrons: 73,
    period: 6,
    group: 5,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Transition Metal",
    atomicRadius: 2.1,
    electroNegativity: 1.5,
    firstIonization: 7.5496,
    density: 16.7,
    meltingPoint: 3269.15,
    boilingPoint: 5731,
    numberOfIsotopes: 19,
    discoverer: "Ekeberg",
  },
  {
    atomicNumber: 74,
    element: "Wolfram",
    symbol: "W",
    atomicMass: 183.84,
    numberOfNeutrons: 110,
    numberOfProtons: 74,
    numberOfElectrons: 74,
    period: 6,
    group: 6,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Transition Metal",
    atomicRadius: 2,
    electroNegativity: 2.36,
    firstIonization: 7.864,
    density: 19.3,
    meltingPoint: 3680.15,
    boilingPoint: 5828,
    numberOfIsotopes: 22,
    discoverer: "J. and F. d'Elhuyar",
  },
  {
    atomicNumber: 75,
    element: "Rhenium",
    symbol: "Re",
    atomicMass: 186.207,
    numberOfNeutrons: 111,
    numberOfProtons: 75,
    numberOfElectrons: 75,
    period: 6,
    group: 7,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Transition Metal",
    atomicRadius: 2,
    electroNegativity: 1.9,
    firstIonization: 7.8335,
    density: 21,
    meltingPoint: 3453.15,
    boilingPoint: 5869,
    numberOfIsotopes: 21,
    discoverer: "Noddack, Berg, and Tacke",
  },
  {
    atomicNumber: 76,
    element: "Osmium",
    symbol: "Os",
    atomicMass: 190.23,
    numberOfNeutrons: 114,
    numberOfProtons: 76,
    numberOfElectrons: 76,
    period: 6,
    group: 8,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Transition Metal",
    atomicRadius: 1.9,
    electroNegativity: 2.2,
    firstIonization: 8.4382,
    density: 22.6,
    meltingPoint: 3300.15,
    boilingPoint: 5285,
    numberOfIsotopes: 19,
    discoverer: "Tennant",
  },
  {
    atomicNumber: 77,
    element: "Iridium",
    symbol: "Ir",
    atomicMass: 192.217,
    numberOfNeutrons: 115,
    numberOfProtons: 77,
    numberOfElectrons: 77,
    period: 6,
    group: 9,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Transition Metal",
    atomicRadius: 1.9,
    electroNegativity: 2.2,
    firstIonization: 8.967,
    density: 22.6,
    meltingPoint: 2716.15,
    boilingPoint: 4701,
    numberOfIsotopes: 25,
    discoverer: "Tennant",
  },
  {
    atomicNumber: 78,
    element: "Platinum",
    symbol: "Pt",
    atomicMass: 195.084,
    numberOfNeutrons: 117,
    numberOfProtons: 78,
    numberOfElectrons: 78,
    period: 6,
    group: 10,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Transition Metal",
    atomicRadius: 1.8,
    electroNegativity: 2.28,
    firstIonization: 8.9587,
    density: 21.5,
    meltingPoint: 2045.15,
    boilingPoint: 4098,
    numberOfIsotopes: 32,
    discoverer: "Ulloa/Wood",
  },
  {
    atomicNumber: 79,
    element: "Gold",
    symbol: "Au",
    atomicMass: 196.967,
    numberOfNeutrons: 118,
    numberOfProtons: 79,
    numberOfElectrons: 79,
    period: 6,
    group: 11,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Transition Metal",
    atomicRadius: 1.8,
    electroNegativity: 2.54,
    firstIonization: 9.2255,
    density: 19.3,
    meltingPoint: 1337.73,
    boilingPoint: 3129,
    numberOfIsotopes: 21,
    discoverer: "Prehistoric",
  },
  {
    atomicNumber: 80,
    element: "Mercury",
    symbol: "Hg",
    atomicMass: 200.59,
    numberOfNeutrons: 121,
    numberOfProtons: 80,
    numberOfElectrons: 80,
    period: 6,
    group: 12,
    phase: "liq",
    radioactive: false,
    natural: true,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Transition Metal",
    atomicRadius: 1.8,
    electroNegativity: 2,
    firstIonization: 10.4375,
    density: 13.5,
    meltingPoint: 234.43,
    boilingPoint: 630,
    numberOfIsotopes: 26,
    discoverer: "Prehistoric",
  },
  {
    atomicNumber: 81,
    element: "Thallium",
    symbol: "Tl",
    atomicMass: 204.383,
    numberOfNeutrons: 123,
    numberOfProtons: 81,
    numberOfElectrons: 81,
    period: 6,
    group: 13,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Metal",
    atomicRadius: 2.1,
    electroNegativity: 2.04,
    firstIonization: 6.1082,
    density: 11.9,
    meltingPoint: 577.15,
    boilingPoint: 1746,
    numberOfIsotopes: 28,
    discoverer: "Crookes",
  },
  {
    atomicNumber: 82,
    element: "Lead",
    symbol: "Pb",
    atomicMass: 207.2,
    numberOfNeutrons: 125,
    numberOfProtons: 82,
    numberOfElectrons: 82,
    period: 6,
    group: 14,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Metal",
    atomicRadius: 1.8,
    electroNegativity: 2.33,
    firstIonization: 7.4167,
    density: 11.3,
    meltingPoint: 600.75,
    boilingPoint: 2022,
    numberOfIsotopes: 29,
    discoverer: "Prehistoric",
  },
  {
    atomicNumber: 83,
    element: "Bismuth",
    symbol: "Bi",
    atomicMass: 208.98,
    numberOfNeutrons: 126,
    numberOfProtons: 83,
    numberOfElectrons: 83,
    period: 6,
    group: 15,
    phase: "solid",
    radioactive: false,
    natural: true,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Metal",
    atomicRadius: 1.6,
    electroNegativity: 2.02,
    firstIonization: 7.2856,
    density: 9.81,
    meltingPoint: 544.67,
    boilingPoint: 1837,
    numberOfIsotopes: 19,
    discoverer: "Geoffroy the Younger",
  },
  {
    atomicNumber: 84,
    element: "Polonium",
    symbol: "Po",
    atomicMass: 210,
    numberOfNeutrons: 126,
    numberOfProtons: 84,
    numberOfElectrons: 84,
    period: 6,
    group: 16,
    phase: "solid",
    radioactive: true,
    natural: true,
    metal: false,
    nonmetal: false,
    metalloid: true,
    type: "Metalloid",
    atomicRadius: 1.5,
    electroNegativity: 2,
    firstIonization: 8.417,
    density: 9.32,
    meltingPoint: 527.15,
    boilingPoint: 1235,
    numberOfIsotopes: 34,
    discoverer: "Curie",
  },
  {
    atomicNumber: 85,
    element: "Astatine",
    symbol: "At",
    atomicMass: 210,
    numberOfNeutrons: 125,
    numberOfProtons: 85,
    numberOfElectrons: 85,
    period: 6,
    group: 17,
    phase: "solid",
    radioactive: true,
    natural: true,
    metal: false,
    nonmetal: true,
    metalloid: false,
    type: "Noble Gas",
    atomicRadius: 1.4,
    electroNegativity: 2.2,
    firstIonization: 9.3,
    density: 7,
    meltingPoint: 575.15,
    boilingPoint: 610,
    numberOfIsotopes: 21,
    discoverer: "Corson et al.",
  },
  {
    atomicNumber: 86,
    element: "Radon",
    symbol: "Rn",
    atomicMass: 222,
    numberOfNeutrons: 136,
    numberOfProtons: 86,
    numberOfElectrons: 86,
    period: 6,
    group: 18,
    phase: "gas",
    radioactive: true,
    natural: true,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Alkali Metal",
    atomicRadius: 1.3,
    firstIonization: 10.7485,
    density: 0.00973,
    meltingPoint: 202.15,
    boilingPoint: 211.3,
    numberOfIsotopes: 20,
    discoverer: "Dorn",
  },
  {
    atomicNumber: 87,
    element: "Francium",
    symbol: "Fr",
    atomicMass: 223,
    numberOfNeutrons: 136,
    numberOfProtons: 87,
    numberOfElectrons: 87,
    period: 7,
    group: 1,
    phase: "solid",
    radioactive: true,
    natural: true,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Alkaline Earth Metal",
    electroNegativity: 0.7,
    firstIonization: 4.0727,
    density: 1.87,
    meltingPoint: 300.15,
    boilingPoint: 950,
    numberOfIsotopes: 21,
    discoverer: "Perey",
  },
  {
    atomicNumber: 88,
    element: "Radium",
    symbol: "Ra",
    atomicMass: 226,
    numberOfNeutrons: 138,
    numberOfProtons: 88,
    numberOfElectrons: 88,
    period: 7,
    group: 2,
    phase: "solid",
    radioactive: true,
    natural: true,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Actinide",
    electroNegativity: 0.9,
    firstIonization: 5.2784,
    density: 5.5,
    meltingPoint: 973.15,
    boilingPoint: 2010,
    numberOfIsotopes: 15,
    discoverer: "Pierre and Marie Curie",
  },
  {
    atomicNumber: 89,
    element: "Actinium",
    symbol: "Ac",
    atomicMass: 227,
    numberOfNeutrons: 138,
    numberOfProtons: 89,
    numberOfElectrons: 89,
    period: 7,
    group: 3,
    phase: "solid",
    radioactive: true,
    natural: true,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Actinide",
    electroNegativity: 1.1,
    firstIonization: 5.17,
    density: 10.1,
    meltingPoint: 1323.15,
    boilingPoint: 3471,
    numberOfIsotopes: 11,
    discoverer: "Debierne/Giesel",
  },
  {
    atomicNumber: 90,
    element: "Thorium",
    symbol: "Th",
    atomicMass: 232.038,
    numberOfNeutrons: 142,
    numberOfProtons: 90,
    numberOfElectrons: 90,
    period: 7,
    phase: "solid",
    radioactive: true,
    natural: true,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Actinide",
    electroNegativity: 1.3,
    firstIonization: 6.3067,
    density: 11.7,
    meltingPoint: 2028.15,
    boilingPoint: 5061,
    numberOfIsotopes: 12,
    discoverer: "Berzelius",
  },
  {
    atomicNumber: 91,
    element: "Protactinium",
    symbol: "Pa",
    atomicMass: 231.036,
    numberOfNeutrons: 140,
    numberOfProtons: 91,
    numberOfElectrons: 91,
    period: 7,
    phase: "solid",
    radioactive: true,
    natural: true,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Actinide",
    electroNegativity: 1.5,
    firstIonization: 5.89,
    density: 15.4,
    meltingPoint: 1873.15,
    boilingPoint: 4300,
    numberOfIsotopes: 14,
    discoverer: "Hahn and Meitner",
  },
  {
    atomicNumber: 92,
    element: "Uranium",
    symbol: "U",
    atomicMass: 238.029,
    numberOfNeutrons: 146,
    numberOfProtons: 92,
    numberOfElectrons: 92,
    period: 7,
    phase: "solid",
    radioactive: true,
    natural: true,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Actinide",
    electroNegativity: 1.38,
    firstIonization: 6.1941,
    density: 19,
    meltingPoint: 1405.15,
    boilingPoint: 4404,
    numberOfIsotopes: 15,
    discoverer: "Peligot",
  },
  {
    atomicNumber: 93,
    element: "Neptunium",
    symbol: "Np",
    atomicMass: 237,
    numberOfNeutrons: 144,
    numberOfProtons: 93,
    numberOfElectrons: 93,
    period: 7,
    phase: "artificial",
    radioactive: true,
    natural: false,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Actinide",
    electroNegativity: 1.36,
    firstIonization: 6.2657,
    density: 20.5,
    meltingPoint: 913.15,
    boilingPoint: 4273,
    numberOfIsotopes: 153,
    discoverer: "McMillan and Abelson",
  },
  {
    atomicNumber: 94,
    element: "Plutonium",
    symbol: "Pu",
    atomicMass: 244,
    numberOfNeutrons: 150,
    numberOfProtons: 94,
    numberOfElectrons: 94,
    period: 7,
    phase: "artificial",
    radioactive: true,
    natural: false,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Actinide",
    electroNegativity: 1.28,
    firstIonization: 6.0262,
    density: 19.8,
    meltingPoint: 913.15,
    boilingPoint: 3501,
    numberOfIsotopes: 163,
    discoverer: "Seaborg et al.",
  },
  {
    atomicNumber: 95,
    element: "Americium",
    symbol: "Am",
    atomicMass: 243,
    numberOfNeutrons: 148,
    numberOfProtons: 95,
    numberOfElectrons: 95,
    period: 7,
    phase: "artificial",
    radioactive: true,
    natural: false,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Actinide",
    electroNegativity: 1.3,
    firstIonization: 5.9738,
    density: 13.7,
    meltingPoint: 1267.15,
    boilingPoint: 2880,
    numberOfIsotopes: 133,
    discoverer: "Seaborg et al.",
  },
  {
    atomicNumber: 96,
    element: "Curium",
    symbol: "Cm",
    atomicMass: 247,
    numberOfNeutrons: 151,
    numberOfProtons: 96,
    numberOfElectrons: 96,
    period: 7,
    phase: "artificial",
    radioactive: true,
    natural: false,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Actinide",
    electroNegativity: 1.3,
    firstIonization: 5.9915,
    density: 13.5,
    meltingPoint: 1340.15,
    boilingPoint: 3383,
    numberOfIsotopes: 133,
    discoverer: "Seaborg et al.",
  },
  {
    atomicNumber: 97,
    element: "Berkelium",
    symbol: "Bk",
    atomicMass: 247,
    numberOfNeutrons: 150,
    numberOfProtons: 97,
    numberOfElectrons: 97,
    period: 7,
    phase: "artificial",
    radioactive: true,
    natural: false,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Actinide",
    electroNegativity: 1.3,
    firstIonization: 6.1979,
    density: 14.8,
    meltingPoint: 1259.15,
    boilingPoint: 983,
    numberOfIsotopes: 83,
    discoverer: "Seaborg et al.",
  },
  {
    atomicNumber: 98,
    element: "Californium",
    symbol: "Cf",
    atomicMass: 251,
    numberOfNeutrons: 153,
    numberOfProtons: 98,
    numberOfElectrons: 98,
    period: 7,
    phase: "artificial",
    radioactive: true,
    natural: false,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Actinide",
    electroNegativity: 1.3,
    firstIonization: 6.2817,
    density: 15.1,
    meltingPoint: 1925.15,
    boilingPoint: 1173,
    numberOfIsotopes: 123,
    discoverer: "Seaborg et al.",
  },
  {
    atomicNumber: 99,
    element: "Einsteinium",
    symbol: "Es",
    atomicMass: 252,
    numberOfNeutrons: 153,
    numberOfProtons: 99,
    numberOfElectrons: 99,
    period: 7,
    phase: "artificial",
    radioactive: true,
    natural: false,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Actinide",
    electroNegativity: 1.3,
    firstIonization: 6.42,
    density: 13.5,
    meltingPoint: 1133.15,
    numberOfIsotopes: 123,
    discoverer: "Ghiorso et al.",
  },
  {
    atomicNumber: 100,
    element: "Fermium",
    symbol: "Fm",
    atomicMass: 257,
    numberOfNeutrons: 157,
    numberOfProtons: 100,
    numberOfElectrons: 100,
    period: 7,
    phase: "artificial",
    radioactive: true,
    natural: false,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Actinide",
    electroNegativity: 1.3,
    firstIonization: 6.5,
    numberOfIsotopes: 103,
    discoverer: "Ghiorso et al.",
  },
  {
    atomicNumber: 101,
    element: "Mendelevium",
    symbol: "Md",
    atomicMass: 258,
    numberOfNeutrons: 157,
    numberOfProtons: 101,
    numberOfElectrons: 101,
    period: 7,
    phase: "artificial",
    radioactive: true,
    natural: false,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Actinide",
    electroNegativity: 1.3,
    firstIonization: 6.58,
    numberOfIsotopes: 33,
    discoverer: "Ghiorso et al.",
  },
  {
    atomicNumber: 102,
    element: "Nobelium",
    symbol: "No",
    atomicMass: 259,
    numberOfNeutrons: 157,
    numberOfProtons: 102,
    numberOfElectrons: 102,
    period: 7,
    phase: "artificial",
    radioactive: true,
    natural: false,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Actinide",
    electroNegativity: 1.3,
    firstIonization: 6.65,
    numberOfIsotopes: 73,
    discoverer: "Ghiorso et al.",
  },
  {
    atomicNumber: 103,
    element: "Lawrencium",
    symbol: "Lr",
    atomicMass: 262,
    numberOfNeutrons: 159,
    numberOfProtons: 103,
    numberOfElectrons: 103,
    period: 7,
    phase: "artificial",
    radioactive: true,
    natural: false,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Actinide",
    numberOfIsotopes: 203,
    discoverer: "Ghiorso et al.",
  },
  {
    atomicNumber: 104,
    element: "Rutherfordium",
    symbol: "Rf",
    atomicMass: 261,
    numberOfNeutrons: 157,
    numberOfProtons: 104,
    numberOfElectrons: 104,
    period: 7,
    group: 4,
    phase: "artificial",
    radioactive: true,
    natural: false,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Transactinide",
    density: 18.1,
    discoverer: "Ghiorso et al.",
  },
  {
    atomicNumber: 105,
    element: "Dubnium",
    symbol: "Db",
    atomicMass: 262,
    numberOfNeutrons: 157,
    numberOfProtons: 105,
    numberOfElectrons: 105,
    period: 7,
    group: 5,
    phase: "artificial",
    radioactive: true,
    natural: false,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Transactinide",
    density: 39,
    discoverer: "Ghiorso et al.",
  },
  {
    atomicNumber: 106,
    element: "Seaborgium",
    symbol: "Sg",
    atomicMass: 266,
    numberOfNeutrons: 160,
    numberOfProtons: 106,
    numberOfElectrons: 106,
    period: 7,
    group: 6,
    phase: "artificial",
    radioactive: true,
    natural: false,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Transactinide",
    density: 35,
    discoverer: "Ghiorso et al.",
  },
  {
    atomicNumber: 107,
    element: "Bohrium",
    symbol: "Bh",
    atomicMass: 264,
    numberOfNeutrons: 157,
    numberOfProtons: 107,
    numberOfElectrons: 107,
    period: 7,
    group: 7,
    phase: "artificial",
    radioactive: true,
    natural: false,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Transactinide",
    density: 37,
    discoverer: "Armbruster and M�nzenberg",
  },
  {
    atomicNumber: 108,
    element: "Hassium",
    symbol: "Hs",
    atomicMass: 267,
    numberOfNeutrons: 159,
    numberOfProtons: 108,
    numberOfElectrons: 108,
    period: 7,
    group: 8,
    phase: "artificial",
    radioactive: true,
    natural: false,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Transactinide",
    density: 41,
    discoverer: "Armbruster and M�nzenberg",
  },
  {
    atomicNumber: 109,
    element: "Meitnerium",
    symbol: "Mt",
    atomicMass: 268,
    numberOfNeutrons: 159,
    numberOfProtons: 109,
    numberOfElectrons: 109,
    period: 7,
    group: 9,
    phase: "artificial",
    radioactive: true,
    natural: false,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Transactinide",
    density: 35,
    discoverer: "GSI, Darmstadt, West Germany",
  },
  {
    atomicNumber: 110,
    element: "Darmstadtium",
    symbol: "Ds",
    atomicMass: 271,
    numberOfNeutrons: 161,
    numberOfProtons: 110,
    numberOfElectrons: 110,
    period: 7,
    group: 10,
    phase: "artificial",
    radioactive: true,
    natural: false,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Transactinide",
  },
  {
    atomicNumber: 111,
    element: "Roentgenium",
    symbol: "Rg",
    atomicMass: 272,
    numberOfNeutrons: 161,
    numberOfProtons: 111,
    numberOfElectrons: 111,
    period: 7,
    group: 11,
    phase: "artificial",
    radioactive: true,
    natural: false,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Transactinide",
  },
  {
    atomicNumber: 112,
    element: "Copernicium",
    symbol: "Cn",
    atomicMass: 285,
    numberOfNeutrons: 173,
    numberOfProtons: 112,
    numberOfElectrons: 112,
    period: 7,
    group: 12,
    phase: "artificial",
    radioactive: true,
    natural: false,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Transactinide",
  },
  {
    atomicNumber: 113,
    element: "Nihonium",
    symbol: "Nh",
    atomicMass: 284,
    numberOfNeutrons: 171,
    numberOfProtons: 113,
    numberOfElectrons: 113,
    period: 7,
    group: 13,
    phase: "artificial",
    radioactive: true,
    natural: false,
    metal: true,
    nonmetal: false,
    metalloid: false,
  },
  {
    atomicNumber: 114,
    element: "Flerovium",
    symbol: "Fl",
    atomicMass: 289,
    numberOfNeutrons: 175,
    numberOfProtons: 114,
    numberOfElectrons: 114,
    period: 7,
    group: 14,
    phase: "artificial",
    radioactive: true,
    natural: false,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Transactinide",
  },
  {
    atomicNumber: 115,
    element: "Moscovium",
    symbol: "Mc",
    atomicMass: 288,
    numberOfNeutrons: 173,
    numberOfProtons: 115,
    numberOfElectrons: 115,
    period: 7,
    group: 15,
    phase: "artificial",
    radioactive: true,
    natural: false,
    metal: true,
    nonmetal: false,
    metalloid: false,
  },
  {
    atomicNumber: 116,
    element: "Livermorium",
    symbol: "Lv",
    atomicMass: 292,
    numberOfNeutrons: 176,
    numberOfProtons: 116,
    numberOfElectrons: 116,
    period: 7,
    group: 16,
    phase: "artificial",
    radioactive: true,
    natural: false,
    metal: true,
    nonmetal: false,
    metalloid: false,
    type: "Transactinide",
  },
  {
    atomicNumber: 117,
    element: "Tennessine",
    symbol: "Ts",
    atomicMass: 295,
    numberOfNeutrons: 178,
    numberOfProtons: 117,
    numberOfElectrons: 117,
    period: 7,
    group: 17,
    phase: "artificial",
    radioactive: true,
    natural: false,
    metal: false,
    nonmetal: true,
    metalloid: false,
  },
  {
    atomicNumber: 118,
    element: "Oganesson",
    symbol: "Og",
    atomicMass: 294,
    numberOfNeutrons: 176,
    numberOfProtons: 118,
    numberOfElectrons: 118,
    period: 7,
    group: 18,
    phase: "artificial",
    radioactive: true,
    natural: false,
    metal: false,
    nonmetal: true,
    metalloid: false,
    type: "Noble Gas",
  },
];

export default ELEMENTS;
